eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8026/BasicEureka/eureka/
  instance:
    hostname: localhost

server:
  port: 8888
  servlet:
    context-path: /Payment